version: '3.3'

services:

  sdc:
    ports:
      - 18630:18630
    container_name: sdc
    hostname: rollingpin.kabang.lo
    image: streamsets/datacollector:3.18.0-latest
    volumes:
      - ${PWD}/mnt/sdc/sdc.properties:/etc/sdc/sdc.properties
      - ${PWD}/mnt/sdc/ldap-login.conf:/etc/sdc/ldap-login.conf
      - ${PWD}/mnt/sdc/streamsets-libs-extras:/opt/streamsets-datacollector-3.18.0/streamsets-libs-extras
      - ${PWD}/mnt/sdc/streamsets-libs:/opt/streamsets-datacollector-3.18.0/streamsets-libs
      - ${PWD}/mnt/sdc/streamsets-datacollector-user-libs:/opt/streamsets-datacollector-user-libs
      - ${PWD}/mnt/sdc/data:/data
      - ${PWD}/mnt/sdc/logs:/logs

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "Kakaobank Inc."
      LDAP_DOMAIN: "openldap"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_READONLY_USER_USERNAME: "readonly"
      LDAP_READONLY_USER_PASSWORD: "readonly"
      LDAP_RFC2307BIS_SCHEMA: "false"
      LDAP_BACKEND: "mdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      KEEP_EXISTING_CONFIG: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
#    volumes:
#      - ./mnt/openldap/ldap:/var/lib/ldap
#      - ./mnt/openldap/slapd.d:/etc/ldap/slapd.d
#      - ./mnt/certs:/container/service/slapd/assets/certs
    ports:
      - "389:389"
      - "636:636"
    domainname: "openldap" # important: same as hostname
    hostname: "openldap"

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "8080:80"
    depends_on:
      - openldap

  nginx-proxy:
    depends_on:
      - sdc
    image: nginx:1.21.3-alpine
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/mnt/nginx/logs:/etc/nginx/logs
      - ${PWD}/mnt/cert:/etc/nginx/cert
    ports:
      - 443:443
      - 80:80